dist: focal
stages:
  - database

jobs:
  include:
  - stage: database
    env: BUILD=db PGSQL=12 PGIS=3 PGPORT=5433
    language: perl
    perl:
        - "5.28"
        - "5.30"
    addons:
      postgresql: 12
      apt:
        packages:
        - postgresql-12
        - postgresql-12-pgtap
    before_install:
    - sudo apt-get -qq update
    - sudo apt-get install libtap-parser-sourcehandler-pgtap-perl
    - sudo apt-get install pgtap
    - sudo apt-get install -y postgresql-${PGSQL}-postgis-${PGIS}
    - sudo apt-get install libpq-dev libdbd-pg-perl

    install:
        - cpanm --notest App::Sqitch DBD::Pg 
    
    before_script:
    - psql -c "ALTER USER travis WITH PASSWORD 'travis';"
    - export PGPASSWORD=travis
    - psql -U travis -c 'CREATE DATABASE "osm_load";'
    - sqitch deploy 'db:pg://travis@localhost/osm_load'

    script:
    - pg_prove -v -U travis -d "osm_load" t/*.sql
