name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  database:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: travis
          POSTGRES_PASSWORD: travis
          POSTGRES_DB: postgres
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    strategy:
      matrix:
        perl-version: [ '5.40', '5.38' ]

    env:
      PGPORT: 5433
      PGSQL: 12
      PGIS: 3
      PGPASSWORD: travis

    steps:
      - uses: actions/checkout@v4

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client libtap-parser-sourcehandler-pgtap-perl pgtap libpq-dev libdbd-pg-perl sqitch libdbd-pg-perl postgresql-$PGSQL-postgis-$PGIS
          cpanm --notest App::Sqitch DBD::Pg

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p $PGPORT; do sleep 1; done

      - name: Set up test database
        run: |
          psql -h localhost -U travis -p $PGPORT -c "ALTER USER travis WITH PASSWORD 'travis';"
          psql -h localhost -U travis -p $PGPORT -c 'CREATE DATABASE "osm_load";'
          sqitch deploy db:pg://travis@localhost:$PGPORT/osm_load

      - name: Run pgTAP tests
        run: |
          pg_prove -v -U travis -h localhost -p $PGPORT -d osm_load t/*.sql
