name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  database:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgis/postgis:17-3.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    strategy:
      matrix:
        perl-version: [ '5.40', '5.38' ]

    env:
      PGPORT: 5432  # Matches the exposed port in services.postgres
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: postgres

    steps:
      - uses: actions/checkout@v4

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client libtap-parser-sourcehandler-pgtap-perl pgtap libpq-dev libdbd-pg-perl sqitch postgresql-postgis
          cpanm --notest App::Sqitch DBD::Pg

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p $PGPORT; do sleep 1; done

      - name: Set up test database
        run: |
          psql -h localhost -U postgres -p $PGPORT -c 'CREATE DATABASE osm_load;'
          sqitch deploy db:pg://postgres:postgres@localhost:$PGPORT/osm_load

      - name: Run pgTAP tests
        run: |
          pg_prove -v -U postgres -h localhost -p $PGPORT -d osm_load t/*.sql
